### ISSUE TITLE
[Bug]: Chaining 'upload' Command After Successful Execution of 'generate' Command

### ISSUE THREAD

**Issue by misusonu18** [Retail-Cosmos/ioi-city-mall-sales-file#31]
### What happened?

The current scheduling includes two commands: 'generate:ioi-city-mall-sales-files' running daily and 'upload:ioi-city-mall-sales-files' set for execution at 00:30 daily. However, if the 'generate' command is ongoing at the time the 'upload' command is triggered, there is a need for the 'upload' command to wait for the 'generate' process to finish before initiating the upload.

### How to reproduce the bug

$schedule->command('generate:ioi-city-mall-sales-files')->daily();

$schedule->command('upload:ioi-city-mall-sales-files')->dailyAt('00:30');

### Package Version

dev

### PHP Version

8.2

### Laravel Version

10.x

**Comment by gauravmak** [comment]
No need for now. The file will be picked up the next day. We can increase the time between the jobs if there is any possibility for the file generation to take more time.
